# Generated by Django 4.2.3 on 2023-07-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0002_account_account_type_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
        migrations.AddField(
            model_name='saving',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10),
        ),
    ]
