# Generated by Django 4.2.3 on 2023-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0003_check_transaction_type_creditcard_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
