# Generated by Django 4.2.3 on 2023-07-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0004_saving_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='interest_rate',
        ),
    ]
