# Generated by Django 4.2.3 on 2023-07-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0005_remove_saving_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
