# Generated by Django 4.2.3 on 2023-08-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0008_account_credit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_limit',
        ),
    ]
