# Generated by Django 4.2.3 on 2023-08-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0009_remove_creditcard_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='last_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='next_payment_date',
            field=models.DateField(null=True),
        ),
    ]
