# Generated by Django 4.2.3 on 2023-08-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0011_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
